### ISSUE TITLE
Error when trying to execute a sample flow

### ISSUE THREAD

**Issue by leawn** [kestra-io/helm-charts#5]
### Expected Behavior

Expected Behavior is to save the flow successfully

### Actual Behaviour

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/41020077/198321495-0d5b49b3-4038-46ed-987a-d84d84c65d70.png">
When trying to click "Save" button, getting an error message with no description

### Steps To Reproduce

1. AWS EKS cluster: v1.21.14-eks-6d3986b
2. nodeInfo:
      architecture: amd64
      containerRuntimeVersion: docker://20.10.7
      kernelVersion: 5.4.156-83.273.amzn2.x86_64
      kubeProxyVersion: v1.21.5-eks-bc4871b
      kubeletVersion: v1.21.5-eks-bc4871b
      operatingSystem: linux
      osImage: Amazon Linux 2
3. Deployed via kestra-helm-chart:v0.5.0
4. Made the following changes to the values.yaml:
      ```
      deployments.executor.enabled: true,
      deployments.webserver.enabled: true,
      deployments.indexer.enabled: true,
      deployments.scheduler.enabled: true,
      deployments.worker.enabled: true,
      kafka.enabled: true,
      elasticsearch.enabled: true,
      ```
5. When successfully deployed, try to run the sample flow as on: https://kestra.io/docs/developer-guide/flow/
6. Try to save the flow
7. When investigating, found the error in:
    - deployment.apps/kep8ya-kestra-scheduler:
```java.lang.NullPointerException
        at io.kestra.core.runners.RunContext.<init>(RunContext.java:94)
        at io.kestra.core.runners.RunContextFactory.of(RunContextFactory.java:30)
        at io.kestra.core.schedulers.AbstractScheduler.lambda$computeSchedulable$4(AbstractScheduler.java:137)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at io.kestra.core.schedulers.AbstractScheduler.computeSchedulable(AbstractScheduler.java:148)
        at io.kestra.core.runners.FlowListeners.listen(FlowListeners.java:99)
        at io.kestra.core.schedulers.AbstractScheduler.run(AbstractScheduler.java:103)
        at io.kestra.jdbc.runner.JdbcScheduler.run(JdbcScheduler.java:55)
        at io.kestra.cli.commands.servers.SchedulerCommand.call(SchedulerCommand.java:35)
        at io.kestra.cli.commands.servers.SchedulerCommand.call(SchedulerCommand.java:14)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.kestra.cli.App.execute(App.java:67)
        at io.kestra.cli.App.main(App.java:47)
```

    - pod/kep8ya-kestra-standalone-78bd4bff5d-t9qm9 kestra-standalone:
```
  2022-10-27 14:43:14,097 ERROR standalone-runner_2 .c.u.ThreadUncaughtExceptionHandlers Caught an exception 
  in Thread[standalone-runner_2,5,main]. Shutting down.
  java.lang.NullPointerException: null
  at io.kestra.core.runners.RunContext.<init>(RunContext.java:94)
  at io.kestra.core.runners.RunContextFactory.of(RunContextFactory.java:30)
  at io.kestra.core.schedulers.AbstractScheduler.lambda$computeSchedulable$4(AbstractScheduler.java:137)
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
  at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
  at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
  at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
  at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
  at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
  at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
  at io.kestra.core.schedulers.AbstractScheduler.computeSchedulable(AbstractScheduler.java:148)
  at io.kestra.core.runners.FlowListeners.listen(FlowListeners.java:99)
  at io.kestra.core.schedulers.AbstractScheduler.run(AbstractScheduler.java:103)
  at io.kestra.jdbc.runner.JdbcScheduler.run(JdbcScheduler.java:55)
  at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
  2022-10-27 14:43:14,159 WARN  command-shutdown io.kestra.cli.AbstractCommand Receiving shutdown ! Try to graceful 
  exit
```

### Environment Information

- Kestra Version: v0.5.0
- Helm Charts version: v0.5.0

**Comment by tchiotludo** [comment]
As I understand, you have setup an internal storage, the error is firing this as I understand.
It seems that minio is not enabled by default in [old charts version](https://github.com/kestra-io/helm-charts/commit/57e797a97c84655c3c2312728fa5746c95f8d43e#diff-a9c626d3eaadfdc3ef2e9f47a59b893a0ba14c31fe422ea1ebbcf082abf0d73bR130), only last version make a clean install process without any configuration

**Comment by leawn** [comment]
- Deployed in the same environment
- Updated version: kestra-helm-chart:v0.5.1
- Updated configuration: set elasticsearch, kafka to `false`. Now configuration consists out of minio & postgresql
- Everything seems to start up, except for kestra-standalone pod (kestra-standalone container) & kestra-executor. Both of them end up in CrashLoopBackOff

<img width="704" alt="image" src="https://user-images.githubusercontent.com/41020077/199231150-9779d616-2b2b-47b7-add2-c2f1a77532fd.png">

- **`kubectl logs pod/kef12g-kestra-standalone-5c99457659-5brl8 kestra-standalone -n kef12g` produces:**

`2022-11-01 12:14:35,752 INFO  standalone   io.kestra.cli.AbstractCommand Starting Kestra with environments [k8s, cloud, ec2, cli]
2022-11-01 12:14:36,248 INFO  standalone   io.kestra.cli.AbstractCommand Server Running: http://kef12g-kestra-standalone-5c99457659-5brl8:8080, Management server on port http://kef12g-kestra-standalone-5c99457659-5brl8:8081/health
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [storageInterface] of class: io.kestra.core.services.ExecutionService
Message: No bean of type [io.kestra.core.storages.StorageInterface] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new JdbcExecutor() --> JdbcExecutor.executionService --> ExecutionService.storageInterface
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2087)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1603)
        at io.kestra.core.services.$ExecutionService$Definition.injectBean(Unknown Source)
        at io.kestra.core.services.$ExecutionService$Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617)
        at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1603)
        at io.kestra.jdbc.runner.$JdbcExecutor$Definition.injectBean(Unknown Source)
        at io.kestra.jdbc.runner.$JdbcExecutor$Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:867)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:859)
        at io.kestra.core.runners.StandAloneRunner.run(StandAloneRunner.java:50)
        at io.kestra.cli.commands.servers.StandAloneCommand.call(StandAloneCommand.java:62)
        at io.kestra.cli.commands.servers.StandAloneCommand.call(StandAloneCommand.java:18)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.kestra.cli.App.execute(App.java:67)
        at io.kestra.cli.App.main(App.java:47)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.kestra.core.storages.StorageInterface] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2805)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617)
        at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065)
        ... 41 more`


- **`kubectl logs pod/kef12g-kestra-executor-7b5b77dbf-j9dqc -n kef12g` produces:**

`2022-11-01 12:14:26,612 INFO  executor     io.kestra.cli.AbstractCommand Starting Kestra with environments [k8s, cloud, ec2, cli]
2022-11-01 12:14:27,187 INFO  executor     io.kestra.cli.AbstractCommand Server Running: http://kef12g-kestra-executor-7b5b77dbf-j9dqc:8080, Management server on port http://kef12g-kestra-executor-7b5b77dbf-j9dqc:8081/health
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [storageInterface] of class: io.kestra.core.services.ExecutionService
Message: No bean of type [io.kestra.core.storages.StorageInterface] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new JdbcExecutor() --> JdbcExecutor.executionService --> ExecutionService.storageInterface
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2087)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1603)
        at io.kestra.core.services.$ExecutionService$Definition.injectBean(Unknown Source)
        at io.kestra.core.services.$ExecutionService$Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617)
        at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1603)
        at io.kestra.jdbc.runner.$JdbcExecutor$Definition.injectBean(Unknown Source)
        at io.kestra.jdbc.runner.$JdbcExecutor$Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:867)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:859)
        at io.kestra.cli.commands.servers.ExecutorCommand.call(ExecutorCommand.java:34)
        at io.kestra.cli.commands.servers.ExecutorCommand.call(ExecutorCommand.java:14)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.kestra.cli.App.execute(App.java:67)
        at io.kestra.cli.App.main(App.java:47)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.kestra.core.storages.StorageInterface] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2805)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617)
        at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065)
        ... 40 more`

**Comment by tchiotludo** [comment]
Can you share you the secrets generated by helm charts ? 
The error meaning there is no configuration for minio, do you have `minio.enabled: true` ?

**Comment by leawn** [comment]
Minio is enabled by default in the helm chart v0.5.1
Also, as you can see from the screenshot, **deployment.apps/kef12g-minio** is ready.

**Comment by tchiotludo** [comment]
can you share the secrets generated please ?

**Comment by leawn** [comment]
Yes, sure, I'll redeploy the application
